//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportesUdec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambiente
    {
        public int Ambiente_Id { get; set; }
        public string Ambiente_Nombre { get; set; }
        public int idLugar { get; set; }
    }
}
