//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportesUdec.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Usuario
    {
       
        public int Usuario_Id { get; set; }
       
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public string Fecha { get; set; }
        public Nullable<int> Rol_Id { get; set; }
        public string Token { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
